### ISSUE TITLE
No numbers are showing up

### ISSUE THREAD

**Issue by AndrewPetz** [weidizhang/Ethereum-Portfolio#1]
[Screenshot](http://i.imgur.com/sAACC3J.png)

[CSV file](https://ghostbin.com/paste/9a5hf)

**Comment by weidizhang** [comment]
https://github.com/weidizhang/Ethereum-Portfolio/blob/master/README.md#using-with-google-chrome-without-a-local-server

**Comment by AndrewPetz** [comment]
Sorry, I should have specified. I'm using Firefox.

**Comment by weidizhang** [comment]
Please take a screenshot of the console and show it here

**Comment by weidizhang** [comment]
Oh, also, I see you have sells in the your CSV, not supported at the moment

**Comment by AndrewPetz** [comment]
Ok that's probably it then. I'll check it when I get home. Thanks!
